spring:
  profiles:
    active:
    - dev
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true    

jwt:
  secret: ZWNvbW1lcmNlLXNwcmluZy1ib290LWp3dC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudA==
  expiration: 3600000 # 1 hour in milliseconds
  
app:
  pagination:
    slice-enabled-for:
      - product  
    